services:
  aircnc.api:
    image: aircnc.api
    build:
      context: .
      dockerfile: AirCnC.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=AirCnCDb;User=sa;Password=Admin123;TrustServerCertificate=False;Encrypt=False;
      - JWTSettings__AccessTokenExpiryInMinutes=0.2
      - JWTSettings__RefreshTokenExpiryInMinutes=0.5
    depends_on: 
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123
    ports:
      - "1433:1433"
    volumes:
      - aircncdata:/var/opt/mssql
volumes:
    aircncdata:
      
