# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pbl6-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b7f077698e984e089569cd09e077fbdf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bbab4b410bf94a47b28d380274876a5d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: index.docker.io/pp311/pbl6:latest
        file: ./AirCnc_Backend/AirCnC.API/Dockerfile.prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pbl6-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_10890efa7b4d45eda96b642d6119e5af }}
        images: 'index.docker.io/pp311/pbl6:latest'
